import os
import resend
import uuid

resend_api_key = os.getenv("RESEND_API_KEY")
FROM_EMAIL = "contact@usync.gg"

async def send_receipt_email(to: str, display_name: str, total_snapshot_cents: int, event_name: str, id: uuid.UUID) -> None:
    """
    Asynchronous function to send the autogenerated receipt email to the buyer.

    ::param to the string containing the buyer's email
    ::param display_name the name to mention in the email
    ::param total_snapshot_cents int containing the total paid by the buyer
    ::param event_name the string containing the event's name
    ::param id uuid4 of the buyer's payment id produced by Stripe
    """

    total_dollars = total_snapshot_cents / 100

    html = f"""
    <html>
    <body style="font-family: sans-serif; color: #111111;">
        <h2>You're registered!</h2>
        <p>Hi {display_name},</p>
        <p>Your payment of <strong>${total_dollars:.2f}</strong> was received and your registration is confirmed for {event_name}.</p>
        <p>Your Receipt ID should you have any issue is ${id}</p>
        <p>Thanks for signing up on usync.gg.</p>
    </body>
    </html>
    """

    await resend.Emails.send_async({
        "from": FROM_EMAIL,
        "to": [to],
        "subject": "Your registration is confirmed",
        "html": html,
    })

    return None

async def send_host_confirmation(to: str, event_name: str, player_info: list[dict], custom_fields: dict, pass_snapshot_cents: int, display_name: str, pass_name: str) -> None:
    """
    Asynchronous function to send the autogenerated confirmation to the host upon a sign up.

    ::param to the string containing the host's email
    ::param event_name the string containing the event's name
    ::param player info the list containing all player information filled out in the form
    ::param custom_fields the dict containing all if any custom information the host wanted to collect
    ::param pass_snapshot_cents the int containing the price of the pass without fees
    ::param display_name the string containing the name of the buyer
    ::param pass_name the string containing the name of the type of pass purchased
    """

    player_cards: list[str] = []

    for index in range(len(player_info)):
        rows: list[str] = []

        for info in player_info[index]:
            if info == "gamertag":
                rows.append(f"<p style=\"margin:2px 0;\"><strong>Gamertag:</strong> {player_info[index][info]}</p>")
            else:
                for socials in player_info[index][info]:
                    label = f"{socials[0].upper()}{socials[1:]}"
                    rows.append(f"<p style=\"margin:2px 0;\"><strong>{label}:</strong> {player_info[index][info][socials]}</p>")

        player_cards.append(f"""
        <div style="border:1px solid #e0e0e0; border-radius:6px; padding:10px 14px; margin-bottom:10px;">
            <p style="margin:0 0 6px 0; font-weight:bold;">Player {index + 1}</p>
            {''.join(rows)}
        </div>
        """)

    custom_section = ""

    if custom_fields:
        custom_lines = "".join(
            f"<p style=\"margin:2px 0; color:#555555;\">{field}: {custom_fields[field]}</p>"
            for field in custom_fields
        )
        custom_section = f"""
        <h3>Additional Info</h3>
        {custom_lines}
        """

    html = f"""
    <html>
    <body style="font-family: sans-serif; color: #111111;">
        <h2>New Sign-up for {event_name}</h2>
        <p>{display_name} signed up for the {pass_name} and paid ${(pass_snapshot_cents / 100):.2f}</p>
        <h3>Players</h3>
        {''.join(player_cards)}
        {custom_section}
    </body>
    </html>
    """

    await resend.Emails.send_async({
        "from": FROM_EMAIL,
        "to": [to],
        "subject": f"New sign-up for {event_name}",
        "html": html,
    })

    return None
