"""Adding host confirmation time to registrations.

Revision ID: 0a6437ce5018
Revises: b8d4a8d1a8db
Create Date: 2026-09-14 18:57:12.412476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6437ce5018'
down_revision: Union[str, Sequence[str], None] = 'b8d4a8d1a8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('host_confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'host_confirmation_sent_at')
    # ### end Alembic commands ###
