"""Adding bracket hosting to user.

Revision ID: 0fbbc7c7b343
Revises: a9811885375a
Create Date: 2026-09-22 16:27:38.628801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbbc7c7b343'
down_revision: Union[str, Sequence[str], None] = 'a9811885375a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bracket_hosting', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bracket_hosting')
    # ### end Alembic commands ###
