"""Adding game to events.

Revision ID: 13c5ced164a7
Revises: ee31d123f5cf
Create Date: 2026-08-20 11:27:11.196290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c5ced164a7'
down_revision: Union[str, Sequence[str], None] = 'ee31d123f5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('game', sa.String(), nullable=False))
    op.add_column('league_events', sa.Column('game', sa.String(), nullable=False))
    op.add_column('wager_events', sa.Column('game', sa.String(), nullable=False))
    op.add_column('xp_events', sa.Column('game', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'game')
    op.drop_column('wager_events', 'game')
    op.drop_column('league_events', 'game')
    op.drop_column('lan_events', 'game')
    # ### end Alembic commands ###
