"""Modifying column name for ids in league parent.

Revision ID: 1d52f62367d6
Revises: de56c2f0bac4
Create Date: 2026-08-24 11:12:22.222556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d52f62367d6'
down_revision: Union[str, Sequence[str], None] = 'de56c2f0bac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_parent_events', sa.Column('id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('league_parent_events_event_id_key'), 'league_parent_events', type_='unique')
    op.create_unique_constraint(None, 'league_parent_events', ['id'])
    op.drop_constraint(op.f('league_parent_events_event_id_fkey'), 'league_parent_events', type_='foreignkey')
    op.create_foreign_key(None, 'league_parent_events', 'events', ['id'], ['id'])
    op.drop_column('league_parent_events', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_parent_events', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'league_parent_events', type_='foreignkey')
    op.create_foreign_key(op.f('league_parent_events_event_id_fkey'), 'league_parent_events', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'league_parent_events', type_='unique')
    op.create_unique_constraint(op.f('league_parent_events_event_id_key'), 'league_parent_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('league_parent_events', 'id')
    # ### end Alembic commands ###
