"""Adding availability to xps.

Revision ID: 2328e2ed3ad9
Revises: de9cc3aa2b10
Create Date: 2026-08-20 14:45:46.301811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2328e2ed3ad9'
down_revision: Union[str, Sequence[str], None] = 'de9cc3aa2b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xp_events', sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'availability')
    # ### end Alembic commands ###
