"""Adding hs and college to leagues and their parents as well as a header image to league parents.

Revision ID: 23829d1102c2
Revises: afbad89f7996
Create Date: 2026-09-03 12:14:23.262816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23829d1102c2'
down_revision: Union[str, Sequence[str], None] = 'afbad89f7996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_events', sa.Column('is_hs', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('league_events', sa.Column('is_college', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('league_parent_events', sa.Column('header_img', sa.String(), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('league_parent_events', sa.Column('is_hs', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('league_parent_events', sa.Column('is_college', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_parent_events', 'is_college')
    op.drop_column('league_parent_events', 'is_hs')
    op.drop_column('league_parent_events', 'header_img')
    op.drop_column('league_events', 'is_college')
    op.drop_column('league_events', 'is_hs')
    # ### end Alembic commands ###
