"""Mass updating user tables. Updating users columns, removing socials, reworking event sites.

Revision ID: 2d729acb3da6
Revises: 0a6437ce5018
Create Date: 2026-09-21 13:11:05.607162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d729acb3da6'
down_revision: Union[str, Sequence[str], None] = '0a6437ce5018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitive_sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('competitive_site_games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['competitive_sites.id'], ),
    sa.PrimaryKeyConstraint('id', 'game')
    )
    op.create_table('player_comp_site_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['competitive_sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('player_id', 'site_id', name='uq_player_id_comp_site_id')
    )
    op.drop_table('socials')
    op.drop_table('cod_site_usernames')
    op.drop_table('event_site_usernames')
    op.add_column('users', sa.Column('is_player', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_host', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('twitch', sa.String(), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('users', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('users', sa.Column('kick', sa.String(), nullable=True))
    op.add_column('users', sa.Column('discord', sa.String(), nullable=True))
    op.add_column('users', sa.Column('instagram', sa.String(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('ix_users_username_host_unique', 'users', ['username'], unique=True, postgresql_where=sa.text('is_host = true'))
    op.create_index('ix_users_username_player_unique', 'users', ['username'], unique=True, postgresql_where=sa.text('is_player = true'))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_username_player_unique', table_name='users', postgresql_where=sa.text('is_player = true'))
    op.drop_index('ix_users_username_host_unique', table_name='users', postgresql_where=sa.text('is_host = true'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'discord')
    op.drop_column('users', 'kick')
    op.drop_column('users', 'youtube')
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'twitch')
    op.drop_column('users', 'is_host')
    op.drop_column('users', 'is_player')
    op.create_table('event_site_usernames',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_site_usernames_pkey'))
    )
    op.create_table('cod_site_usernames',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cmg', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('gb', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['event_site_usernames.id'], name=op.f('cod_site_usernames_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cod_site_usernames_pkey')),
    sa.UniqueConstraint('cmg', name=op.f('cod_site_usernames_cmg_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('gb', name=op.f('cod_site_usernames_gb_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('socials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instagram', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discord', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('youtube', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('socials_pkey')),
    sa.UniqueConstraint('discord', name=op.f('socials_discord_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('instagram', name=op.f('socials_instagram_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('twitch', name=op.f('socials_twitch_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('twitter', name=op.f('socials_twitter_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('youtube', name=op.f('socials_youtube_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('player_comp_site_accounts')
    op.drop_table('competitive_site_games')
    op.drop_table('competitive_sites')
    # ### end Alembic commands ###
