"""Adding a drop val to each event table if we need to drop the whole table.

Revision ID: 30f5eb209ca0
Revises: 13c5ced164a7
Create Date: 2026-08-20 12:10:55.753005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f5eb209ca0'
down_revision: Union[str, Sequence[str], None] = '13c5ced164a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('drop_val', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('league_events', sa.Column('drop_val', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('wager_events', sa.Column('drop_val', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('xp_events', sa.Column('drop_val', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'drop_val')
    op.drop_column('wager_events', 'drop_val')
    op.drop_column('league_events', 'drop_val')
    op.drop_column('lan_events', 'drop_val')
    # ### end Alembic commands ###
