"""Created all host data models and users models necessary at this time along with their initial architecture

Revision ID: 31d57bb7bfd0
Revises: 7f7f27fa7c5b
Create Date: 2026-06-08 19:08:11.935365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d57bb7bfd0'
down_revision: Union[str, Sequence[str], None] = '7f7f27fa7c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
