"""Adding columns to events.

Revision ID: 3cfbfa2c7fd5
Revises: 2328e2ed3ad9
Create Date: 2026-08-23 10:02:11.217335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfbfa2c7fd5'
down_revision: Union[str, Sequence[str], None] = '2328e2ed3ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('path', sa.String(), nullable=False))
    op.add_column('league_events', sa.Column('path', sa.String(), nullable=False))
    op.add_column('league_events', sa.Column('group', sa.String(), nullable=False))
    op.add_column('wager_events', sa.Column('path', sa.String(), nullable=False))
    op.add_column('xp_events', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'path')
    op.drop_column('wager_events', 'path')
    op.drop_column('league_events', 'group')
    op.drop_column('league_events', 'path')
    op.drop_column('lan_events', 'path')
    # ### end Alembic commands ###
