"""Updating cod tournament structure to have a site_id

Revision ID: 3f7f6899665a
Revises: bbdc07dc57e4
Create Date: 2026-06-16 14:08:53.022011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7f6899665a'
down_revision: Union[str, Sequence[str], None] = 'bbdc07dc57e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('site_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'cod_tournaments', ['site_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cod_tournaments', type_='unique')
    op.drop_column('cod_tournaments', 'site_id')
    # ### end Alembic commands ###
