"""Modifying Socials and Hosts tables

Revision ID: 4a021ddca0e8
Revises: ee221adb973c
Create Date: 2026-06-09 14:44:29.027416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a021ddca0e8'
down_revision: Union[str, Sequence[str], None] = 'ee221adb973c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('event_site', sa.String(), nullable=True))
    op.add_column('socials', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('socials', sa.Column('twitch', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'socials', ['youtube'])
    op.create_unique_constraint(None, 'socials', ['twitch'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'socials', type_='unique')
    op.drop_constraint(None, 'socials', type_='unique')
    op.drop_column('socials', 'twitch')
    op.drop_column('socials', 'youtube')
    op.drop_column('hosts', 'event_site')
    # ### end Alembic commands ###
