"""Dropping game from event registrations.

Revision ID: 4c35be21fb3b
Revises: a83844e8acdc
Create Date: 2026-09-10 20:45:47.692171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c35be21fb3b'
down_revision: Union[str, Sequence[str], None] = 'a83844e8acdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'game')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('game', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
