"""Reverting lan_events fee_details to a list

Revision ID: 50ac023cf8e0
Revises: 30f5eb209ca0
Create Date: 2026-08-20 12:37:08.984608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ac023cf8e0'
down_revision: Union[str, Sequence[str], None] = '30f5eb209ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lan_events', 'fee_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               postgresql_using='NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lan_events', 'fee_details',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='NULL')
    # ### end Alembic commands ###
