"""Adding form fields to passes.

Revision ID: 590e95a285ec
Revises: 639c22f083ca
Create Date: 2026-09-11 14:40:51.665906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '590e95a285ec'
down_revision: Union[str, Sequence[str], None] = '639c22f083ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_pass_tiers', sa.Column('form_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('event_pass_tiers', sa.Column('team_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_pass_tiers', 'team_size')
    op.drop_column('event_pass_tiers', 'form_fields')
    # ### end Alembic commands ###
