"""Adding canonical usernames and shifting uniqueness.

Revision ID: 5b5dee451a84
Revises: ac976915650f
Create Date: 2026-10-02 19:13:06.201350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5dee451a84'
down_revision: Union[str, Sequence[str], None] = 'ac976915650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('canonical_username', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_username_host_unique'), table_name='users', postgresql_where='(is_host = true)')
    op.create_index('ix_users_username_host_unique', 'users', ['canonical_username'], unique=True, postgresql_where=sa.text('is_host = true'))
    op.drop_index(op.f('ix_users_username_player_unique'), table_name='users', postgresql_where='(is_player = true)')
    op.create_index('ix_users_username_player_unique', 'users', ['canonical_username'], unique=True, postgresql_where=sa.text('is_player = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_player_unique', table_name='users', postgresql_where=sa.text('is_player = true'))
    op.create_index(op.f('ix_users_username_player_unique'), 'users', ['username'], unique=True, postgresql_where='(is_player = true)')
    op.drop_index('ix_users_username_host_unique', table_name='users', postgresql_where=sa.text('is_host = true'))
    op.create_index(op.f('ix_users_username_host_unique'), 'users', ['username'], unique=True, postgresql_where='(is_host = true)')
    op.drop_column('users', 'canonical_username')
    # ### end Alembic commands ###
