"""Adding new parents table and updating league group field.

Revision ID: 60e2d3e8b97c
Revises: 3cfbfa2c7fd5
Create Date: 2026-08-23 11:21:08.132572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e2d3e8b97c'
down_revision: Union[str, Sequence[str], None] = '3cfbfa2c7fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_parent_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('name')
    )
    op.create_foreign_key(None, 'league_events', 'league_parent_events', ['group'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_events', type_='foreignkey')
    op.drop_table('league_parent_events')
    # ### end Alembic commands ###
