"""updating tournaments table to include event id

Revision ID: 61550c59e508
Revises: 98f5e12b1579
Create Date: 2026-06-26 13:30:39.547275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61550c59e508'
down_revision: Union[str, Sequence[str], None] = '98f5e12b1579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('event_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_tournaments', 'event_id')
    # ### end Alembic commands ###
