"""Adding maximum and sell count to passes.

Revision ID: 639c22f083ca
Revises: 4c35be21fb3b
Create Date: 2026-09-11 13:22:05.532944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639c22f083ca'
down_revision: Union[str, Sequence[str], None] = '4c35be21fb3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_pass_tiers', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('event_pass_tiers', sa.Column('sold_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_pass_tiers', 'sold_count')
    op.drop_column('event_pass_tiers', 'capacity')
    # ### end Alembic commands ###
