"""Adding column with always True value to allow for full table drop

Revision ID: 7dbc3af4c363
Revises: acaac295b331
Create Date: 2026-06-19 13:35:35.841530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbc3af4c363'
down_revision: Union[str, Sequence[str], None] = 'acaac295b331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('drop_val', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_tournaments', 'drop_val')
    # ### end Alembic commands ###
