"""Creating event registration tables.

Revision ID: 7e81c680a815
Revises: 85f22e8e25ee
Create Date: 2026-09-10 16:57:52.963860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e81c680a815'
down_revision: Union[str, Sequence[str], None] = '85f22e8e25ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_pass_tiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('requires_team', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'tier_name', name='uq_event_pass_tiers_event_tier_name')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('pass_tier_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('team_name_normalized', sa.String(), nullable=True),
    sa.Column('contact_username', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('player_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_snapshot_cents', sa.Integer(), nullable=False),
    sa.Column('fee_snapshot_cents', sa.Integer(), nullable=False),
    sa.Column('total_snapshot_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['pass_tier_id'], ['event_pass_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index('uq_registrations_event_team_name', 'event_registrations', ['event_id', 'team_name_normalized'], unique=True, postgresql_where=sa.text('team_name_normalized IS NOT NULL'))
    op.create_index('uq_registrations_individual_contact', 'event_registrations', ['event_id', 'pass_tier_id', 'contact_email'], unique=True, postgresql_where=sa.text('team_name_normalized IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_registrations_individual_contact', table_name='event_registrations', postgresql_where=sa.text('team_name_normalized IS NULL'))
    op.drop_index('uq_registrations_event_team_name', table_name='event_registrations', postgresql_where=sa.text('team_name_normalized IS NOT NULL'))
    op.drop_table('event_registrations')
    op.drop_table('event_pass_tiers')
    # ### end Alembic commands ###
