"""Initial table creation for Tournaments, CodTournaments, FormData, and GeneralForm

Revision ID: 7f7f27fa7c5b
Revises: bd13139ea79e
Create Date: 2026-06-04 21:59:33.544845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7f27fa7c5b'
down_revision: Union[str, Sequence[str], None] = 'bd13139ea79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments_parent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cod_tournaments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('entry', sa.String(), nullable=False),
    sa.Column('region', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('requirements', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('skill', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('team_size', sa.String(), nullable=False),
    sa.Column('gamemode', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_form',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('captain_username', sa.String(), nullable=False),
    sa.Column('player_usernames', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('player_socials', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('team_email', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('games', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_form')
    op.drop_table('cod_tournaments')
    op.drop_table('tournaments_parent')
    op.drop_table('form_parent')
    # ### end Alembic commands ###
