"""Adding seo fields to data.

Revision ID: 85f22e8e25ee
Revises: e5a84c0f471f
Create Date: 2026-09-08 15:26:32.829244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f22e8e25ee'
down_revision: Union[str, Sequence[str], None] = 'e5a84c0f471f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('lan_events', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('league_events', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('league_events', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('league_parent_events', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('league_parent_events', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('wager_events', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('wager_events', sa.Column('seo_description', sa.String(), nullable=True))
    op.add_column('xp_events', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('xp_events', sa.Column('seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'seo_description')
    op.drop_column('xp_events', 'seo_title')
    op.drop_column('wager_events', 'seo_description')
    op.drop_column('wager_events', 'seo_title')
    op.drop_column('league_parent_events', 'seo_description')
    op.drop_column('league_parent_events', 'seo_title')
    op.drop_column('league_events', 'seo_description')
    op.drop_column('league_events', 'seo_title')
    op.drop_column('lan_events', 'seo_description')
    op.drop_column('lan_events', 'seo_title')
    # ### end Alembic commands ###
