"""Adding uniqueness to ids.

Revision ID: 8decc0fd0146
Revises: 50ac023cf8e0
Create Date: 2026-08-20 13:48:52.313528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8decc0fd0146'
down_revision: Union[str, Sequence[str], None] = '50ac023cf8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['id'])
    op.create_unique_constraint(None, 'lan_events', ['event_id'])
    op.create_unique_constraint(None, 'league_events', ['event_id'])
    op.create_unique_constraint(None, 'wager_events', ['event_id'])
    op.create_unique_constraint(None, 'xp_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xp_events', type_='unique')
    op.drop_constraint(None, 'wager_events', type_='unique')
    op.drop_constraint(None, 'league_events', type_='unique')
    op.drop_constraint(None, 'lan_events', type_='unique')
    op.drop_constraint(None, 'events', type_='unique')
    # ### end Alembic commands ###
