"""Removing site ids and making them the primary & foreign keys as the tournament ids. Didn't need tournament ids.

Revision ID: 94cdfccae61d
Revises: ef8bfd924ce3
Create Date: 2026-06-19 15:34:44.777767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cdfccae61d'
down_revision: Union[str, Sequence[str], None] = 'ef8bfd924ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cod_tournaments_site_id_key'), 'cod_tournaments', type_='unique')
    op.drop_constraint(op.f('cod_tournaments_tournament_id_fkey'), 'cod_tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'cod_tournaments', 'tournaments_parent', ['site_id'], ['id'])
    op.drop_column('cod_tournaments', 'tournament_id')
    op.drop_constraint(op.f('tournaments_parent_site_id_key'), 'tournaments_parent', type_='unique')
    op.drop_column('tournaments_parent', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_parent', sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tournaments_parent_site_id_key'), 'tournaments_parent', ['site_id'], postgresql_nulls_not_distinct=False)
    op.add_column('cod_tournaments', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cod_tournaments', type_='foreignkey')
    op.create_foreign_key(op.f('cod_tournaments_tournament_id_fkey'), 'cod_tournaments', 'tournaments_parent', ['tournament_id'], ['id'])
    op.create_unique_constraint(op.f('cod_tournaments_site_id_key'), 'cod_tournaments', ['site_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
