"""Adding a lastmod time to all events for sitemap generation.

Revision ID: 96415aae4f9a
Revises: b5f47b4ce065
Create Date: 2026-09-04 21:45:00.201689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96415aae4f9a'
down_revision: Union[str, Sequence[str], None] = 'b5f47b4ce065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('league_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('league_parent_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('wager_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('xp_events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'updated_at')
    op.drop_column('wager_events', 'updated_at')
    op.drop_column('league_parent_events', 'updated_at')
    op.drop_column('league_events', 'updated_at')
    op.drop_column('lan_events', 'updated_at')
    # ### end Alembic commands ###
