"""Adding unique to ids.

Revision ID: 98f5e12b1579
Revises: 94cdfccae61d
Create Date: 2026-06-19 15:46:09.596761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f5e12b1579'
down_revision: Union[str, Sequence[str], None] = '94cdfccae61d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cod_tournaments', ['site_id'])
    op.create_unique_constraint(None, 'tournaments_parent', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments_parent', type_='unique')
    op.drop_constraint(None, 'cod_tournaments', type_='unique')
    # ### end Alembic commands ###
