"""Upgrading registrations to accept org_twitter.

Revision ID: a239e540852c
Revises: e982531c4962
Create Date: 2026-09-11 18:51:51.408976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a239e540852c'
down_revision: Union[str, Sequence[str], None] = 'e982531c4962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registrations', sa.Column('org_twitter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_registrations', 'org_twitter')
    # ### end Alembic commands ###
