"""Updating user models to sort fields and updating schemas to handle sign up form payload.

Revision ID: a9811885375a
Revises: 2d729acb3da6
Create Date: 2026-09-22 14:24:38.811759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9811885375a'
down_revision: Union[str, Sequence[str], None] = '2d729acb3da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'competitive_sites', ['id'])
    op.add_column('hosts', sa.Column('other_games', sa.String(), nullable=True))
    op.add_column('hosts', sa.Column('organization', sa.String(), nullable=False))
    op.add_column('hosts', sa.Column('host_country', sa.String(), nullable=False))
    op.add_column('hosts', sa.Column('event_types', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_constraint(op.f('hosts_email_key'), 'hosts', type_='unique')
    op.drop_constraint(op.f('hosts_username_key'), 'hosts', type_='unique')
    op.drop_column('hosts', 'username')
    op.drop_column('hosts', 'email')
    op.drop_column('hosts', 'event_site')
    op.create_unique_constraint(None, 'player_comp_site_accounts', ['id'])
    op.add_column('players', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('players', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('players', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('players', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('players', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('players', sa.Column('country', sa.String(), nullable=True))
    op.add_column('players', sa.Column('other_games', sa.String(), nullable=True))
    op.drop_constraint(op.f('players_email_key'), 'players', type_='unique')
    op.drop_constraint(op.f('players_username_key'), 'players', type_='unique')
    op.drop_column('players', 'username')
    op.drop_column('players', 'email')
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.add_column('players', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('players_username_key'), 'players', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('players_email_key'), 'players', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('players', 'other_games')
    op.drop_column('players', 'country')
    op.drop_column('players', 'date_of_birth')
    op.drop_column('players', 'gender')
    op.drop_column('players', 'phone_number')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    op.drop_constraint(None, 'player_comp_site_accounts', type_='unique')
    op.add_column('hosts', sa.Column('event_site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hosts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hosts', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('hosts_username_key'), 'hosts', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('hosts_email_key'), 'hosts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('hosts', 'event_types')
    op.drop_column('hosts', 'host_country')
    op.drop_column('hosts', 'organization')
    op.drop_column('hosts', 'other_games')
    op.drop_constraint(None, 'competitive_sites', type_='unique')
    # ### end Alembic commands ###
