"""Updating cod tournament structure to include the site

Revision ID: acaac295b331
Revises: 3f7f6899665a
Create Date: 2026-06-16 14:42:25.178301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaac295b331'
down_revision: Union[str, Sequence[str], None] = '3f7f6899665a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('site', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cod_tournaments', 'site')
    # ### end Alembic commands ###
