"""Modifying group foreign key to accept null.

Revision ID: af02dea25f5e
Revises: 1d52f62367d6
Create Date: 2026-08-24 11:33:09.543971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af02dea25f5e'
down_revision: Union[str, Sequence[str], None] = '1d52f62367d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_events', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('league_events', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
