"""Adding a drop val to league parent events.

Revision ID: afbad89f7996
Revises: af02dea25f5e
Create Date: 2026-08-24 14:34:56.862813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbad89f7996'
down_revision: Union[str, Sequence[str], None] = 'af02dea25f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_parent_events', sa.Column('drop_val', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_parent_events', 'drop_val')
    # ### end Alembic commands ###
