"""Adding latitude and longitude to LANs

Revision ID: b5f47b4ce065
Revises: 23829d1102c2
Create Date: 2026-09-04 13:45:33.041652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f47b4ce065'
down_revision: Union[str, Sequence[str], None] = '23829d1102c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('lat', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    op.add_column('lan_events', sa.Column('long', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lan_events', 'long')
    op.drop_column('lan_events', 'lat')
    # ### end Alembic commands ###
