"""Adding host name and host user id to event passes.

Revision ID: b8d4a8d1a8db
Revises: 73d9d676ac88
Create Date: 2026-09-14 18:12:17.465711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d4a8d1a8db'
down_revision: Union[str, Sequence[str], None] = '73d9d676ac88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_pass_tiers', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('event_pass_tiers', sa.Column('host_email', sa.String(), server_default=sa.text("'contact@usync.gg'"), nullable=True))
    op.create_foreign_key(None, 'event_pass_tiers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_pass_tiers', type_='foreignkey')
    op.drop_column('event_pass_tiers', 'host_email')
    op.drop_column('event_pass_tiers', 'user_id')
    # ### end Alembic commands ###
