"""Modified Tournament Parent and Child table structure

Revision ID: bbdc07dc57e4
Revises: 4a021ddca0e8
Create Date: 2026-06-15 18:00:50.344337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdc07dc57e4'
down_revision: Union[str, Sequence[str], None] = '4a021ddca0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('is_1v1', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_2v2', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_3v3', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_4v4', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_na', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_eu', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_latam', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_usa', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_apac', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_worldwide', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_pc', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_console', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_all_platforms', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_novice', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_amateur', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_expert', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_agent', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_master', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_challenger', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_all_skill', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_free', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_eco', sa.Boolean(), nullable=False))
    op.add_column('cod_tournaments', sa.Column('is_elite', sa.Boolean(), nullable=False))
    op.drop_column('cod_tournaments', 'id')
    op.add_column('tournaments_parent', sa.Column('site_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tournaments_parent', ['site_id'])
    op.drop_column('tournaments_parent', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments_parent', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tournaments_parent', type_='unique')
    op.drop_column('tournaments_parent', 'site_id')
    op.add_column('cod_tournaments', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('cod_tournaments', 'is_elite')
    op.drop_column('cod_tournaments', 'is_eco')
    op.drop_column('cod_tournaments', 'is_paid')
    op.drop_column('cod_tournaments', 'is_free')
    op.drop_column('cod_tournaments', 'is_all_skill')
    op.drop_column('cod_tournaments', 'is_challenger')
    op.drop_column('cod_tournaments', 'is_master')
    op.drop_column('cod_tournaments', 'is_agent')
    op.drop_column('cod_tournaments', 'is_expert')
    op.drop_column('cod_tournaments', 'is_amateur')
    op.drop_column('cod_tournaments', 'is_novice')
    op.drop_column('cod_tournaments', 'is_all_platforms')
    op.drop_column('cod_tournaments', 'is_console')
    op.drop_column('cod_tournaments', 'is_pc')
    op.drop_column('cod_tournaments', 'is_worldwide')
    op.drop_column('cod_tournaments', 'is_apac')
    op.drop_column('cod_tournaments', 'is_usa')
    op.drop_column('cod_tournaments', 'is_latam')
    op.drop_column('cod_tournaments', 'is_eu')
    op.drop_column('cod_tournaments', 'is_na')
    op.drop_column('cod_tournaments', 'is_4v4')
    op.drop_column('cod_tournaments', 'is_3v3')
    op.drop_column('cod_tournaments', 'is_2v2')
    op.drop_column('cod_tournaments', 'is_1v1')
    # ### end Alembic commands ###
