"""Updating unique constraints for event tables.

Revision ID: c5e0c7d1d5ca
Revises: 6b7fee1d70f5
Create Date: 2026-09-05 00:39:41.443281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e0c7d1d5ca'
down_revision: Union[str, Sequence[str], None] = '6b7fee1d70f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lan_events_game_path', 'lan_events', ['game', 'path'])
    op.create_unique_constraint('uq_league_events_game_path', 'league_events', ['game', 'path'])
    op.create_unique_constraint('uq_league_parent_events_game_path', 'league_parent_events', ['game', 'path'])
    op.create_unique_constraint('uq_wager_events_game_path', 'wager_events', ['game', 'path'])
    op.create_unique_constraint('uq_xp_events_game_path', 'xp_events', ['game', 'path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_xp_events_game_path', 'xp_events', type_='unique')
    op.drop_constraint('uq_wager_events_game_path', 'wager_events', type_='unique')
    op.drop_constraint('uq_league_parent_events_game_path', 'league_parent_events', type_='unique')
    op.drop_constraint('uq_league_events_game_path', 'league_events', type_='unique')
    op.drop_constraint('uq_lan_events_game_path', 'lan_events', type_='unique')
    # ### end Alembic commands ###
