"""Adding game col to league parents.

Revision ID: c70c097ec5b6
Revises: 60e2d3e8b97c
Create Date: 2026-08-24 10:26:40.996983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70c097ec5b6'
down_revision: Union[str, Sequence[str], None] = '60e2d3e8b97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_parent_events', sa.Column('game', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'league_parent_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league_parent_events', type_='unique')
    op.drop_column('league_parent_events', 'game')
    # ### end Alembic commands ###
