"""Adding fee_details to xps.

Revision ID: cc0149dff431
Revises: c5e0c7d1d5ca
Create Date: 2026-09-06 00:50:02.348009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc0149dff431'
down_revision: Union[str, Sequence[str], None] = 'c5e0c7d1d5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xp_events', sa.Column('fee_details', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xp_events', 'fee_details')
    # ### end Alembic commands ###
