"""Updating users fields.

Revision ID: d1f2747c96cb
Revises: a425eec16c76
Create Date: 2026-09-24 15:17:57.036083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1f2747c96cb'
down_revision: Union[str, Sequence[str], None] = 'a425eec16c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('other_roles', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('other_role_detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'other_role_detail')
    op.drop_column('users', 'other_roles')
    # ### end Alembic commands ###
