"""Adding path col to league parents.

Revision ID: de56c2f0bac4
Revises: c70c097ec5b6
Create Date: 2026-08-24 10:27:26.809178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de56c2f0bac4'
down_revision: Union[str, Sequence[str], None] = 'c70c097ec5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_parent_events', sa.Column('path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_parent_events', 'path')
    # ### end Alembic commands ###
