"""Changing fees to fee_details for consistency.

Revision ID: de9cc3aa2b10
Revises: 8decc0fd0146
Create Date: 2026-08-20 14:21:46.734978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de9cc3aa2b10'
down_revision: Union[str, Sequence[str], None] = '8decc0fd0146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wager_events', sa.Column('fee_details', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('wager_events', 'fees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wager_events', sa.Column('fees', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('wager_events', 'fee_details')
    # ### end Alembic commands ###
