"""Adding usync pass flag to lan events.

Revision ID: dec2298570a7
Revises: 590e95a285ec
Create Date: 2026-09-11 15:01:00.879241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec2298570a7'
down_revision: Union[str, Sequence[str], None] = '590e95a285ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('usync_pass', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lan_events', 'usync_pass')
    # ### end Alembic commands ###
