"""Modifying uniqueness of lan events. Removing the coupled contraint and only applying to path.

Revision ID: e5a84c0f471f
Revises: cc0149dff431
Create Date: 2026-09-06 14:36:37.696768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a84c0f471f'
down_revision: Union[str, Sequence[str], None] = 'cc0149dff431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_lan_events_game_path'), 'lan_events', type_='unique')
    op.create_unique_constraint(None, 'lan_events', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lan_events', type_='unique')
    op.create_unique_constraint(op.f('uq_lan_events_game_path'), 'lan_events', ['game', 'path'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
