"""Adding player fields to passes.

Revision ID: e982531c4962
Revises: dec2298570a7
Create Date: 2026-09-11 18:39:16.214374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e982531c4962'
down_revision: Union[str, Sequence[str], None] = 'dec2298570a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_pass_tiers', sa.Column('player_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_pass_tiers', 'player_fields')
    # ### end Alembic commands ###
