"""Updating event table structures.

Revision ID: ec7ec6257341
Revises: 61550c59e508
Create Date: 2026-08-20 10:40:04.831981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec7ec6257341'
down_revision: Union[str, Sequence[str], None] = '61550c59e508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('lan_events', sa.Column('verified', sa.Boolean(), nullable=False))
    op.alter_column('lan_events', 'fee_details',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(fee_details)',
               existing_nullable=False)
    op.drop_constraint(op.f('lan_events_name_key'), 'lan_events', type_='unique')
    op.drop_column('lan_events', 'id')
    op.drop_column('lan_events', 'fee')
    op.add_column('league_events', sa.Column('verified', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('league_events_name_key'), 'league_events', type_='unique')
    op.drop_column('league_events', 'id')
    op.drop_column('league_events', 'fee')
    op.add_column('wager_events', sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('wager_events', sa.Column('verified', sa.Boolean(), nullable=False))
    op.alter_column('wager_events', 'restrictions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(restrictions)',
               existing_nullable=False)
    op.drop_constraint(op.f('wager_events_name_key'), 'wager_events', type_='unique')
    op.drop_column('wager_events', 'id')
    op.add_column('xp_events', sa.Column('verified', sa.Boolean(), nullable=False))
    op.alter_column('xp_events', 'restrictions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='to_jsonb(restrictions)',
               existing_nullable=False)
    op.drop_constraint(op.f('xp_events_name_key'), 'xp_events', type_='unique')
    op.drop_column('xp_events', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xp_events', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('xp_events_name_key'), 'xp_events', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('xp_events', 'restrictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               postgresql_using="ARRAY(SELECT jsonb_array_elements_text(restrictions))",
               existing_nullable=False)
    op.drop_column('xp_events', 'verified')
    op.add_column('wager_events', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('wager_events_name_key'), 'wager_events', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('wager_events', 'restrictions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               postgresql_using="ARRAY(SELECT jsonb_array_elements_text(restrictions))",
               existing_nullable=False)
    op.drop_column('wager_events', 'verified')
    op.drop_column('wager_events', 'availability')
    op.add_column('league_events', sa.Column('fee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('league_events', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('league_events_name_key'), 'league_events', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('league_events', 'verified')
    op.add_column('lan_events', sa.Column('fee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lan_events', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('lan_events_name_key'), 'lan_events', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('lan_events', 'fee_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               postgresql_using="ARRAY(SELECT jsonb_array_elements_text(fee_details))",
               existing_nullable=False)
    op.drop_column('lan_events', 'verified')
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
