"""Created all host data models and users models necessary at this time along with their initial architecture

Revision ID: ee221adb973c
Revises: 31d57bb7bfd0
Create Date: 2026-06-08 19:15:11.151140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee221adb973c'
down_revision: Union[str, Sequence[str], None] = '31d57bb7bfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_site_usernames',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord'),
    sa.UniqueConstraint('instagram'),
    sa.UniqueConstraint('twitter')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cod_site_usernames',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cmg', sa.Uuid(), nullable=True),
    sa.Column('gb', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['event_site_usernames.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cmg'),
    sa.UniqueConstraint('gb')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('games', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('battlenet', sa.String(), nullable=True),
    sa.Column('activision', sa.String(), nullable=True),
    sa.Column('steam', sa.String(), nullable=True),
    sa.Column('riot', sa.String(), nullable=True),
    sa.Column('games', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activision'),
    sa.UniqueConstraint('battlenet'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('riot'),
    sa.UniqueConstraint('steam'),
    sa.UniqueConstraint('username')
    )
    op.create_table('statistics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lan_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('fee', sa.String(), nullable=False),
    sa.Column('fee_details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('header_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lan_statistics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('placing', sa.String(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('proof', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stat_id'], ['statistics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seasonality', sa.String(), nullable=False),
    sa.Column('details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('team_size', sa.String(), nullable=False),
    sa.Column('fee', sa.String(), nullable=False),
    sa.Column('fee_details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('header_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_statistics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('earnings', sa.String(), nullable=True),
    sa.Column('wins', sa.String(), nullable=True),
    sa.Column('losses', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stat_id'], ['statistics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_statistics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('site_url', sa.String(), nullable=True),
    sa.Column('elites', sa.Integer(), nullable=True),
    sa.Column('golds', sa.Integer(), nullable=True),
    sa.Column('silvers', sa.Integer(), nullable=True),
    sa.Column('bronzes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stat_id'], ['statistics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wager_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fees', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('restrictions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('header_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('xp_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('restrictions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('header_img', sa.String(), nullable=False),
    sa.Column('banner_img', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xp_events')
    op.drop_table('wager_events')
    op.drop_table('tournament_statistics')
    op.drop_table('site_statistics')
    op.drop_table('league_events')
    op.drop_table('lan_statistics')
    op.drop_table('lan_events')
    op.drop_table('statistics')
    op.drop_table('players')
    op.drop_table('hosts')
    op.drop_table('events')
    op.drop_table('cod_site_usernames')
    op.drop_table('users')
    op.drop_table('socials')
    op.drop_table('event_site_usernames')
    # ### end Alembic commands ###
