"""Adding archived to LANs.

Revision ID: ee31d123f5cf
Revises: ec7ec6257341
Create Date: 2026-08-20 10:50:26.803717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee31d123f5cf'
down_revision: Union[str, Sequence[str], None] = 'ec7ec6257341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lan_events', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lan_events', 'archived')
    # ### end Alembic commands ###
