"""Adding column with timestamp for queries related to checking expired/upcoming tournaments.

Revision ID: ef8bfd924ce3
Revises: 7dbc3af4c363
Create Date: 2026-06-19 15:12:40.466485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8bfd924ce3'
down_revision: Union[str, Sequence[str], None] = '7dbc3af4c363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cod_tournaments', sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('cod_tournaments', 'drop_val',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cod_tournaments', 'drop_val',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('cod_tournaments', 'starts_at')
    # ### end Alembic commands ###
