"""Revising contact username to accept none as its not integrated yet.

Revision ID: f15d0b7823a6
Revises: 7e81c680a815
Create Date: 2026-09-10 20:16:33.964371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15d0b7823a6'
down_revision: Union[str, Sequence[str], None] = '7e81c680a815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_registrations', 'contact_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'event_registrations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_registrations', type_='unique')
    op.alter_column('event_registrations', 'contact_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
